#!/usr/bin/env bash

(set -x; brew update;)
(set -x; brew upgrade;)

(set -x; brew cleanup -s;)

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
autoUpdates=" (auto_updates)"

casks=( $(brew cask list) )

for cask in ${casks[@]}
do
    # Remove (auto updates) from version
    version=$(brew cask info $cask | sed -n "s/$cask:\ \(.*\)/\1/p")
    version=${version%"$autoUpdates"}
    installed=$(find "/usr/local/Caskroom/$cask" -type d -maxdepth 1 -maxdepth 1 -name "$version")

    if [[ -z $installed ]]; then
        echo "${red}${cask}${reset} requires ${red}update${reset}."
        (set -x; brew cask uninstall $cask --force;)
        (set -x; brew cask install $cask --force;)
    else
        echo "${red}${cask}${reset} is ${green}up-to-date${reset}."
    fi
done